"""Shared data models for the TAO Mining Intelligence Pipeline.

When running inside the Lambda container, the LAMBDA_TASK_ROOT is set to
the src/ directory, so imports use the package name directly (e.g., models.schemas).
For local development, add lambda/src/ to sys.path.
"""

from src.models.enums import (
    Confidence,
    CompetitionTrend,
    EntryBarrierLevel,
    HardwareTier,
    HoldVsSwap,
    MiningStyle,
    PipelineState,
    RewardModel,
    SubnetCategory,
    TaoflowStatus,
)
from src.models.schemas import (
    AlphaPrice,
    AlphaPriceRecord,
    BriefingAlert,
    ChurnMetrics,
    CollectionResult,
    DailyBriefing,
    DeregistrationRisk,
    DerivedMetadata,
    DerivedMetrics,
    DerivedMetricsData,
    EmissionTrend,
    EntryBarrier,
    FinalizationResult,
    HotkeyEarnings,
    HotkeyPosition,
    HotkeySnapshot,
    HotkeyTracking,
    HyperparameterRecord,
    MetadataHeader,
    MetagraphData,
    MetagraphSnapshot,
    Neuron,
    ProcessingResult,
    RegistrationCost,
    RegistrationCostRecord,
    RentalProfitability,
    RewardDistribution,
    RewardDistributionModel,
    ROIEstimate,
    SnapshotMetadata,
    SubnetProfile,
    SubnetProfileBasic,
    SubnetProfileComposability,
    SubnetProfileIntelligence,
    SubnetProfileValidator,
    SubnetProfileWinner,
    SubnetRanking,
    TaoflowHealth,
    TaoPriceRecord,
    ValidatorLandscape,
    WinnerCharacteristics,
)

__all__ = [
    # Enums
    "Confidence",
    "CompetitionTrend",
    "EntryBarrierLevel",
    "HardwareTier",
    "HoldVsSwap",
    "MiningStyle",
    "PipelineState",
    "RewardModel",
    "SubnetCategory",
    "TaoflowStatus",
    # Metadata
    "MetadataHeader",
    "SnapshotMetadata",
    "DerivedMetadata",
    # Raw Schemas
    "AlphaPrice",
    "AlphaPriceRecord",
    "HyperparameterRecord",
    "MetagraphData",
    "MetagraphSnapshot",
    "Neuron",
    "RegistrationCost",
    "RegistrationCostRecord",
    "TaoPriceRecord",
    # Derived Metrics
    "ChurnMetrics",
    "DeregistrationRisk",
    "DerivedMetrics",
    "DerivedMetricsData",
    "EmissionTrend",
    "EntryBarrier",
    "RentalProfitability",
    "RewardDistribution",
    "RewardDistributionModel",
    "ROIEstimate",
    "TaoflowHealth",
    "ValidatorLandscape",
    # Aggregates
    "BriefingAlert",
    "DailyBriefing",
    "SubnetRanking",
    # Subnet Profiles (split for DynamoDB 400KB limit)
    "SubnetProfile",
    "SubnetProfileBasic",
    "SubnetProfileWinner",
    "SubnetProfileValidator",
    "SubnetProfileIntelligence",
    "SubnetProfileComposability",
    "WinnerCharacteristics",
    # Hotkey Tracking
    "HotkeyEarnings",
    "HotkeyPosition",
    "HotkeySnapshot",
    "HotkeyTracking",
    # Pipeline Results
    "CollectionResult",
    "ProcessingResult",
    "FinalizationResult",
]
