#!/usr/bin/env python3
"""Generate kb/metrics-reference.md from structured Metric: blocks in metrics.py.

Usage:
    python scripts/generate_metrics_reference.py

This script parses the `Metric:` blocks in each method's docstring of
MetricsEngine (lambda/src/processor/metrics.py) and produces the living
metrics reference guide. Run this after adding or modifying any metric.

The output file (kb/metrics-reference.md) should NOT be edited manually.
"""

import ast
import re
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
METRICS_FILE = PROJECT_ROOT / "lambda" / "src" / "processor" / "metrics.py"
OUTPUT_FILE = PROJECT_ROOT / "kb" / "metrics-reference.md"


def parse_metric_block(docstring: str) -> dict | None:
    """Extract the Metric: block from a docstring into a dict."""
    if not docstring or "Metric:" not in docstring:
        return None

    # Find the Metric: section — ast.get_docstring() strips leading indent,
    # so keys are at 4-space indent and continuation lines at 8-space indent.
    # The block ends when we hit a line with 0 indent that isn't blank.
    idx = docstring.index("Metric:")
    after_metric = docstring[idx:]
    # Skip the "Metric:\n" header
    lines_after = after_metric.split("\n")[1:]

    block_lines = []
    for line in lines_after:
        # A non-empty line with no leading whitespace terminates the block
        if line.strip() and not line.startswith(" "):
            break
        block_lines.append(line)

    block_text = "\n".join(block_lines)
    result = {}
    current_key = None
    current_lines = []

    for line in block_text.split("\n"):
        # Check for a new key (4-space indented key: value)
        key_match = re.match(r"\s{4}(\w+):\s*(.*)", line)
        if key_match:
            # Save previous key
            if current_key:
                result[current_key] = "\n".join(current_lines).strip()
            current_key = key_match.group(1)
            first_value = key_match.group(2).strip()
            current_lines = [first_value] if first_value and first_value != "|" else []
        elif current_key:
            # Continuation line — strip up to 8 spaces of indent
            stripped = line.rstrip()
            content = re.sub(r"^\s{8}", "", stripped)
            if content or current_lines:  # skip leading blank lines
                current_lines.append(content)

    # Save last key
    if current_key:
        result[current_key] = "\n".join(current_lines).strip()

    return result if result.get("name") else None


def extract_metrics_from_source() -> list[dict]:
    """Parse metrics.py AST and extract all Metric: blocks."""
    source = METRICS_FILE.read_text()
    tree = ast.parse(source)

    metrics = []
    metric_number = 0

    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            docstring = ast.get_docstring(node)
            if not docstring:
                continue
            metric = parse_metric_block(docstring)
            if metric:
                metric_number += 1
                metric["_number"] = metric_number
                metric["_method"] = node.name
                metrics.append(metric)

    return metrics


def render_markdown(metrics: list[dict]) -> str:
    """Render the metrics reference markdown."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# Metrics Reference Guide",
        "",
        "> **Auto-generated** from `lambda/src/processor/metrics.py` structured docstrings.",
        f"> **Last generated**: {now}",
        ">",
        "> **Do NOT edit this file manually.** Update the `Metric:` block in the source",
        "> code and re-run: `python scripts/generate_metrics_reference.py`",
        "",
        "---",
        "",
        "## How to Read This Document",
        "",
        "Each metric has:",
        "- **Formula**: The exact calculation",
        "- **Hypothesis**: What we believe this metric represents and why",
        "- **Usefulness**: How this metric informs decisions (mining, staking, risk)",
        "- **Status**: `PROVEN` | `HYPOTHESIS` | `NEEDS_VALIDATION` | `DEPRECATED`",
        "- **Known Issues**: Current limitations",
        "- **Assumptions**: Things that need validation",
        "",
        "---",
        "",
        "## Status Legend",
        "",
        "| Status | Meaning | Action |",
        "|--------|---------|--------|",
        "| **PROVEN** | Validated against live outcomes or standard formula | Use for automated decisions |",
        "| **HYPOTHESIS** | Logic sound, not validated against outcomes | Use for recommendations, flag uncertainty |",
        "| **NEEDS_VALIDATION** | Known limitations or missing data | Display but don't act on |",
        "| **DEPRECATED** | Replaced or found misleading | Remove from rankings |",
        "",
        "---",
        "",
    ]

    # Summary table
    lines.append("## Metrics Summary")
    lines.append("")
    lines.append("| # | Metric | Status | Mining | Staking | Risk |")
    lines.append("|---|--------|--------|--------|---------|------|")
    for m in metrics:
        mining = "✅" if m.get("usefulness_mining", "").strip() else "—"
        staking = "✅" if m.get("usefulness_staking", "").strip() else "—"
        risk = "✅" if m.get("usefulness_risk", "").strip() else "—"
        lines.append(f"| {m['_number']} | {m['name']} | `{m.get('status', '?')}` | {mining} | {staking} | {risk} |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Detailed sections
    for m in metrics:
        lines.append(f"## Metric {m['_number']}: {m['name']}")
        lines.append("")
        lines.append(f"**Status**: `{m.get('status', 'UNKNOWN')}`")
        lines.append(f"**Source**: `MetricsEngine.{m['_method']}()`")
        lines.append("")

        if m.get("hypothesis"):
            lines.append("### Hypothesis")
            lines.append("")
            lines.append(m["hypothesis"])
            lines.append("")

        if m.get("formula"):
            lines.append("### Formula")
            lines.append("")
            lines.append("```")
            lines.append(m["formula"])
            lines.append("```")
            lines.append("")

        if m.get("output_range"):
            lines.append(f"**Output range**: {m['output_range']}")
            lines.append("")

        # Usefulness table
        has_usefulness = any(m.get(f"usefulness_{k}") for k in ("mining", "staking", "risk"))
        if has_usefulness:
            lines.append("### Usefulness")
            lines.append("")
            lines.append("| Context | How it helps |")
            lines.append("|---------|-------------|")
            if m.get("usefulness_mining"):
                lines.append(f"| Mining | {m['usefulness_mining']} |")
            if m.get("usefulness_staking"):
                lines.append(f"| Staking | {m['usefulness_staking']} |")
            if m.get("usefulness_risk"):
                lines.append(f"| Risk | {m['usefulness_risk']} |")
            lines.append("")

        if m.get("known_issues"):
            lines.append("### Known Issues")
            lines.append("")
            lines.append(m["known_issues"])
            lines.append("")

        if m.get("validated_against"):
            lines.append("### Validated Against")
            lines.append("")
            lines.append(m["validated_against"])
            lines.append("")

        if m.get("assumptions"):
            lines.append("### Assumptions to Validate")
            lines.append("")
            for assumption in m["assumptions"].split("\n"):
                a = assumption.strip().lstrip("- ")
                if a:
                    lines.append(f"- [ ] {a}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Footer
    lines.extend([
        "## How This Document Evolves",
        "",
        "1. **Add/modify a metric** → Update the `Metric:` block in `metrics.py`",
        "2. **Re-generate** → `python scripts/generate_metrics_reference.py`",
        "3. **Validate against outcomes** → Change status from HYPOTHESIS to PROVEN",
        "4. **Find a bug** → Fix the code, update the Metric: block, re-generate",
        "",
        "The source of truth is always the code. This document is a readable view.",
        "",
        "---",
        "",
        "## Future: Configurable Metrics Registry",
        "",
        "When the system reaches 20+ metrics or Stage 7 (OPTIMIZE) needs dynamic",
        "control, refactor to a lightweight registry pattern. Until then, pure",
        "functions in MetricsEngine + structured docstrings + this generator is",
        "sufficient. See `kb/product-vision-roadmap.md` for the full plan.",
    ])

    return "\n".join(lines) + "\n"


def main() -> int:
    if not METRICS_FILE.exists():
        print(f"ERROR: {METRICS_FILE} not found", file=sys.stderr)
        return 1

    metrics = extract_metrics_from_source()
    if not metrics:
        print("ERROR: No Metric: blocks found in source", file=sys.stderr)
        return 1

    output = render_markdown(metrics)
    OUTPUT_FILE.write_text(output)
    print(f"Generated {OUTPUT_FILE} with {len(metrics)} metrics")
    return 0


if __name__ == "__main__":
    sys.exit(main())
